**`NumPy`, short for Numerical Python, is the fundamental package required for high
performance scientific computing and data analysis. It is the foundation on which
nearly all of the higher-level tools for data science in python are built.**

**Some of the things provided by NumPy are:**
- `ndarray`: a fast and space efficient multidimensional array providing vectorized arithmetic operations and sophisticated broadcasting capabilities
- standard mathematical functions for fast operations on entire arrays of data without having to write loops
- tools for reading/writing array  data to disk and working with memory-mapped files
- linear algebra, random number generations


In [1]:
# lets import numpy using the standard convention
import numpy as np

**An `ndarray` is a generic multidimensional container for homogeneous data; that is, all of the elements must be the same type**

- the easiest way to create an array is by using `np.array` function. This accepts any sequence like object including other arrays

In [8]:
# lets create a numpy array

data = np.array([[ 0.9526, -0.246 , -0.8856],
                [ 0.5639, 0.2379, 0.9104]])

data

array([[ 0.9526, -0.246 , -0.8856],
       [ 0.5639,  0.2379,  0.9104]])

In [3]:
# Every array has a shape, a tuple indicating the size of each dimension,

data.shape

(2, 3)

In [4]:
# Every array has a dtype, an object describing the data type of the array:


data.dtype

dtype('float64')

- In addition to np.arrary, there are number of other functions for creating new arrays:
    - `np.zeros`
    - `np.ones`
    - `np.empty`
    - `np.asarray`

In [5]:
print(np.zeros(5))
print()
print(np.zeros((2,3)))
print()
print(np.ones(4))
print()
print(np.ones((2,3)))
print()
print(np.empty(4))
print()
print(np.empty((2,3,2)))

[0. 0. 0. 0. 0.]

[[0. 0. 0.]
 [0. 0. 0.]]

[1. 1. 1. 1.]

[[1. 1. 1.]
 [1. 1. 1.]]

[1. 1. 1. 1.]

[[[-3.10503618e+231 -3.10503618e+231]
  [ 2.96439388e-323  0.00000000e+000]
  [ 6.94889962e-310  6.82116729e-043]]

 [[ 7.48374579e-091  6.87005235e+169]
  [ 5.41846894e-067  1.08516758e-042]
  [ 3.99910963e+252  8.38745808e-309]]]


In [14]:
# use of as array
a = [1,2,3,4,5]
b = np.asarray(a)
print(b)

c = np.asarray([1,2,4,6,'a'])
c

[1 2 3 4 5]


array(['1', '2', '4', '6', 'a'], dtype='<U21')

- **`arange`** is an array valued version of the built-in Python range function

In [6]:
#use of built--in python range
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [7]:
#lets try arange
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

**There is also `np.ones_like` and `np.zeros_like` function.**
- `np.ones_like` takes another array and produces a ones array of the same shape and dtype
- `np.zeros_like` takes another array and produces a zeros array of the same shape and dtype

**`np.eye`** or **`np.identity`** create a square N X N identity matrix(1's on the diagonal and 0's elsewhere)

In [22]:
# examples of above

print(np.ones_like(np.array([1,2,3,4,5])))
print(np.zeros_like(np.array([1,2,3,4,5])))
print(np.eye(5))
print(np.identity(4))

[1 1 1 1 1]
[0 0 0 0 0]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


**You can explicitly convert or cast an array from one data type to another using ndarray's astype method. Example:**

In [23]:
a = np.array([1,2,3,4,5])
b = a.astype(np.float64)
print(a)
print(b)

[1 2 3 4 5]
[1. 2. 3. 4. 5.]


In [32]:
# Should you have an array of strings representing numbers, you can use astype to convert them to numeric form:

numeric_strings = np.array(['1.25', '-9.6'], dtype = np.string_)
numeric_strings.astype(float)

array([ 1.25, -9.6 ])

#### Operations between Arrays and Scalars
- Arrays are important because they enable you to express batch operations on data without writing any for loops. This is usually called vectorization.
- Any arithmetic operations between equal-size arrays applies the operation elementwise
- Operations between differently sized arrays is called broadcasting.

In [37]:
arr = np.array([[1,2,3], [4,5,6]])
print(arr)
print()
print('the multiplication of arr with arr will look like: ' )
print(arr * arr)
print()




[[1 2 3]
 [4 5 6]]

the multiplication of arr with arr will look like: 
[[ 1  4  9]
 [16 25 36]]



In [38]:
# Arithmetic operations with scalars(have single value, the magnitude) performs the operation in each element

arr/2

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ]])

#### Basic Indexing and Slicing
- NumPy array indexing is a rich topic, as there are many ways you may want to selecta subset of your data or individual elements. One-dimensional arrays are simple; on the surface they act similarly to Python lists:

In [52]:
arr = np.arange(10)
arr

# lets slice it, lets get the element at index 4
print(arr[4])

print(arr[2:5])

# replacing values
arr[2:6] = 12

arr

4
[2 3 4]


array([ 0,  1, 12, 12, 12, 12,  6,  7,  8,  9])

- As you can see, if you assign a scalar value to a slice, as in arr[2:6] = 12, the value is propagated (or broadcasted henceforth) to the entire selection. An important first distinction from lists is that array slices are views on the original array. This means that the data is not copied, and any modifications to the view will be reflected in the source array:

In [53]:
arr_slice = arr[2:6]
arr_slice[1] = 1456
arr
arr_slice[:] = 0
arr

array([0, 1, 0, 0, 0, 0, 6, 7, 8, 9])

In [54]:
# if you want a copy of a slice of an ndarray instead of a view, you will need to explicitly copy the array:
arr_slice = arr[2:6].copy()
arr_slice

array([0, 0, 0, 0])